///scrLoadFile()

if !file_exists (working_directory+"\save"+string(global.save)+".txt") or global.save == -1
{
    return false;
}

file = file_text_open_read (working_directory+"\save"+string(global.save)+".txt");

global.secondsFile = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.minutesFile = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.hoursFile = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.ch1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.ch2 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z1_1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z1_1Knux = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z1_1Amy = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z1_B = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z1_BKnux = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z1_BAmy = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z2_1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z2_1Knux = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z2_1Amy = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z2_B = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z2_BKnux = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.Z2_BAmy = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.S1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.S1S = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.S2 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.life = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.gems = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.totalrings = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.getHeart0 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.getHeart1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.seal0 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.seal0A = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.seal0B = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.maxHearts = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.monkeyLearnt = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.elephantLearnt = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.harpyLearnt = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.stomp = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.slide = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.punch = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.drill = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.tornado = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.dialogue0 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.dialogue1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.halfpotions = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.fullpotions = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.autopotions = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.pikeballs = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.superpikeballs = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.fireballs = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.keys = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.d1door = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.mdoor1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.doorpass1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.doorpass2 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.doorpass3 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.ringItem = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.tablet = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.chest1 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.chest2 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.chest3 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.chest4 = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.chest1L = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.chest2L = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.chest3L = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);
global.chest4L = real (base64_decode (file_text_read_string (file)));
file_text_readln (file);

file_text_close (file);
return true;
