///scrSaveFile()

audio_stop_all();

if global.save == -1
   exit;
   
file_delete (working_directory+"\save"+string(global.save)+".txt");
file = file_text_open_write (working_directory+"\save"+string(global.save)+".txt");

file_text_write_string (file, base64_encode (string (global.secondsFile)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.minutesFile)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.hoursFile)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.ch1)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.ch2)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z1_1)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z1_1Knux)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z1_1Amy)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z1_B)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z1_BKnux)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z1_BAmy)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z2_1)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z2_1Knux)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z2_1Amy)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z2_B)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z2_BKnux)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.Z2_BAmy)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.S1)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.S1S)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.S2)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.life)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.gems)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.totalrings)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.getHeart0)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.getHeart1)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.seal0)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.seal0A)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.seal0B)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.maxHearts)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.monkeyLearnt)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.elephantLearnt)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.harpyLearnt)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.stomp)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.slide)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.punch)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.drill)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.tornado)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.dialogue0)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.dialogue1)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.halfpotions)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.fullpotions)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.autopotions)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.pikeballs)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.superpikeballs)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.fireballs)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.keys)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.d1door)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.mdoor)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.doorpass1)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.doorpass2)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.doorpass3)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.ringItem)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.tablet)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.chest1)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.chest2)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.chest3)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.chest4)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.chest1L)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.chest2L)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.chest3L)));
file_text_writeln (file);
file_text_write_string (file, base64_encode (string (global.chest4L)));
file_text_writeln (file);

file_text_close (file);
